const districts = [
  { id: 1, state: "Tamilnadu", district: "Ariyalur" },
  { id: 2, state: "Tamilnadu", district: "Chengalpattu" },
  { id: 3, state: "Tamilnadu", district: "Chennai" },
  { id: 4, state: "Tamilnadu", district: "Coimbatore" },
  { id: 5, state: "Tamilnadu", district: "Cuddalore" },
  { id: 6, state: "Tamilnadu", district: "Dharmapuri" },
  { id: 7, state: "Tamilnadu", district: "Dindigul" },
  { id: 8, state: "Tamilnadu", district: "Erode" },
  { id: 9, state: "Tamilnadu", district: "Kallakurichi" },
  { id: 10, state: "Tamilnadu", district: "Kancheepuram" },
  { id: 11, state: "Tamilnadu", district: "Karur" },
  { id: 12, state: "Tamilnadu", district: "Krishnagiri" },
  { id: 13, state: "Tamilnadu", district: "Madurai" },
  { id: 14, state: "Tamilnadu", district: "Mayiladuthurai" },
  { id: 15, state: "Tamilnadu", district: "Nagapattinam" },
  { id: 16, state: "Tamilnadu", district: "Namakkal" },
  { id: 17, state: "Tamilnadu", district: "Nilgiris" },
  { id: 18, state: "Tamilnadu", district: "Perambalur" },
  { id: 19, state: "Tamilnadu", district: "Pudukkottai" },
  { id: 20, state: "Tamilnadu", district: "Ramanathapuram" },
  { id: 21, state: "Tamilnadu", district: "Ranipet" },
  { id: 22, state: "Tamilnadu", district: "Salem" },
  { id: 23, state: "Tamilnadu", district: "Sivaganga" },
  { id: 24, state: "Tamilnadu", district: "Tenkasi" },
  { id: 25, state: "Tamilnadu", district: "Thanjavur" },
  { id: 26, state: "Tamilnadu", district: "Theni" },
  { id: 27, state: "Tamilnadu", district: "Thoothukudi" },
  { id: 28, state: "Tamilnadu", district: "Tiruchirappalli" },
  { id: 29, state: "Tamilnadu", district: "Tirunelveli" },
  { id: 30, state: "Tamilnadu", district: "Tirupathur" },
  { id: 31, state: "Tamilnadu", district: "Tiruppur" },
  { id: 32, state: "Tamilnadu", district: "Tiruvallur" },
  { id: 33, state: "Tamilnadu", district: "Tiruvannamalai" },
  { id: 34, state: "Tamilnadu", district: "Tiruvarur" },
  { id: 35, state: "Tamilnadu", district: "Vellore" },
  { id: 36, state: "Tamilnadu", district: "Viluppuram" },
  { id: 37, state: "Tamilnadu", district: "Virudhunagar" },
  { id: 38, state: "Tamilnadu", district: "Kanniyakumari" },
  // Kerala/Pondicherry
  { id: 39, state: "Kerala", district: "Thiruvananthapuram" },
  { id: 40, state: "Kerala", district: "Kollam" },
  { id: 41, state: "Kerala", district: "Pathanamthitta" },
  { id: 42, state: "Kerala", district: "Alappuzha" },
  { id: 43, state: "Kerala", district: "Kottayam" },
  { id: 44, state: "Kerala", district: "Idukki" },
  { id: 45, state: "Kerala", district: "Ernakulam" },
  { id: 46, state: "Kerala", district: "Thrissur" },
  { id: 47, state: "Kerala", district: "Palakkad" },
  { id: 48, state: "Kerala", district: "Malappuram" },
  { id: 49, state: "Kerala", district: "Kozhikode" },
  { id: 50, state: "Kerala", district: "Wayanad" },
  { id: 51, state: "Kerala", district: "Kannur" },
  { id: 52, state: "Kerala", district: "Kasaragod" },
  { id: 53, state: "Kerala", district: "Puducherry" },
  { id: 54, state: "Kerala", district: "Karaikal" },
  { id: 55, state: "Kerala", district: "Mahe" },
  { id: 56, state: "Kerala", district: "Yanam" },
  // Karnataka/Andhra Pradesh/Telangana
  { id: 57, state: "Others", district: "Bengaluru Urban" },
  { id: 58, state: "Others", district: "Bengaluru Rural" },
  { id: 59, state: "Others", district: "Ramanagara" },
  { id: 60, state: "Others", district: "Kolar" },
  { id: 61, state: "Others", district: "Chikballapur" },
  { id: 62, state: "Others", district: "Tumkur" },
  { id: 63, state: "Others", district: "Chikmagalur" },
  { id: 64, state: "Others", district: "Hassan" },
  { id: 65, state: "Others", district: "Kodagu" },
  { id: 66, state: "Others", district: "Dakshina Kannada" },
  { id: 67, state: "Others", district: "Udupi" },
  { id: 68, state: "Others", district: "Uttara Kannada" },
  { id: 69, state: "Others", district: "Shivamogga" },
  { id: 70, state: "Others", district: "Davangere" },
  { id: 71, state: "Others", district: "Chitradurga" },
  { id: 72, state: "Others", district: "Ballari" },
  { id: 73, state: "Others", district: "Vikarabad" },
  { id: 74, state: "Others", district: "Raichur" },
  { id: 75, state: "Others", district: "Gadag" },
  { id: 76, state: "Others", district: "Bagalkot" },
  { id: 77, state: "Others", district: "Belagavi" },
  { id: 78, state: "Others", district: "Vijayapura" },
  { id: 79, state: "Others", district: "Yadgir" },
  { id: 80, state: "Others", district: "Anantapur" },
  { id: 81, state: "Others", district: "Chittoor" },
  { id: 82, state: "Others", district: "Kadapa" },
  { id: 83, state: "Others", district: "Nellore" },
  { id: 84, state: "Others", district: "Prakasam" },
  { id: 85, state: "Others", district: "Bapatla" },
  { id: 86, state: "Others", district: "Guntur" },
  { id: 87, state: "Others", district: "Krishna" },
  { id: 88, state: "Others", district: "West Godavari" },
  { id: 89, state: "Others", district: "East Godavari" },
  { id: 90, state: "Others", district: "Visakhapatnam" },
  { id: 91, state: "Others", district: "Vizianagaram" },
  { id: 92, state: "Others", district: "Srikakulam" },
  { id: 93, state: "Others", district: "Adilabad" },
  { id: 94, state: "Others", district: "Komaram Bheem Asifabad" },
  { id: 95, state: "Others", district: "Nirmal" },
  { id: 96, state: "Others", district: "Peddapalli" },
  { id: 97, state: "Others", district: "Jangaon" },
  { id: 98, state: "Others", district: "Warangal Rural" },
  { id: 99, state: "Others", district: "Warangal Urban" },
  { id: 100, state: "Others", district: "Huzurabad" },
  { id: 101, state: "Others", district: "Siddipet" },
  { id: 102, state: "Others", district: "Medchal-Malkajgiri" },
  { id: 103, state: "Others", district: "Hyderabad" },
  { id: 104, state: "Others", district: "Ranga Reddy" },
  { id: 105, state: "Others", district: "Vikarabad" },
  { id: 106, state: "Others", district: "Sangareddy" },
  { id: 107, state: "Others", district: "Yadadri Bhuvanagiri" }
];

export default districts;
