const districts = [
  { id: 1, state: "Tamilnadu", district: "Ariyalur" },
  { id: 2, state: "Tamilnadu", district: "Chengalpattu" },
  { id: 3, state: "Tamilnadu", district: "Chennai" },
  { id: 4, state: "Tamilnadu", district: "Coimbatore" },
  { id: 5, state: "Tamilnadu", district: "Cuddalore" },
  { id: 6, state: "Tamilnadu", district: "Dharmapuri" },
  { id: 7, state: "Tamilnadu", district: "Dindigul" },
  { id: 8, state: "Tamilnadu", district: "Erode" },
  { id: 9, state: "Tamilnadu", district: "Kallakurichi" },
  { id: 10, state: "Tamilnadu", district: "Kancheepuram" },
  { id: 11, state: "Tamilnadu", district: "Karur" },
  { id: 12, state: "Tamilnadu", district: "Krishnagiri" },
  { id: 13, state: "Tamilnadu", district: "Madurai" },
  { id: 14, state: "Tamilnadu", district: "Mayiladuthurai" },
  { id: 15, state: "Tamilnadu", district: "Nagapattinam" },
  { id: 16, state: "Tamilnadu", district: "Namakkal" },
  { id: 17, state: "Tamilnadu", district: "Nilgiris" },
  { id: 18, state: "Tamilnadu", district: "Perambalur" },
  { id: 19, state: "Tamilnadu", district: "Pudukkottai" },
  { id: 20, state: "Tamilnadu", district: "Ramanathapuram" },
  { id: 21, state: "Tamilnadu", district: "Ranipet" },
  { id: 22, state: "Tamilnadu", district: "Salem" },
  { id: 23, state: "Tamilnadu", district: "Sivaganga" },
  { id: 24, state: "Tamilnadu", district: "Tenkasi" },
  { id: 25, state: "Tamilnadu", district: "Thanjavur" },
  { id: 26, state: "Tamilnadu", district: "Theni" },
  { id: 27, state: "Tamilnadu", district: "Thoothukudi" },
  { id: 28, state: "Tamilnadu", district: "Tiruchirappalli" },
  { id: 29, state: "Tamilnadu", district: "Tirunelveli" },
  { id: 30, state: "Tamilnadu", district: "Tirupathur" },
  { id: 31, state: "Tamilnadu", district: "Tiruppur" },
  { id: 32, state: "Tamilnadu", district: "Tiruvallur" },
  { id: 33, state: "Tamilnadu", district: "Tiruvannamalai" },
  { id: 34, state: "Tamilnadu", district: "Tiruvarur" },
  { id: 35, state: "Tamilnadu", district: "Vellore" },
  { id: 36, state: "Tamilnadu", district: "Viluppuram" },
  { id: 37, state: "Tamilnadu", district: "Virudhunagar" },
  { id: 38, state: "Tamilnadu", district: "Kanniyakumari" }
];

export default districts;
