import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/user/Navbar";
import Layout from "@/components/layouts/user/Layout";
import { Providers } from "@/lib/providers";
import { QueryProvider } from "@/lib/QueryProvider";
import Script from "next/script"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TVK - CUP",
  description: "Generated by create next app",
};

type Props = {
  children?: React.ReactNode
}

export default function RootLayout({
  children,
}: Readonly<Props>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#000] mx-auto`}
      >
        {/* Google Analytics */}
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-SYKM675PL1" strategy="afterInteractive" />
        <Script id="gtag-init" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-SYKM675PL1');`}
        </Script>
        <Providers>
          <QueryProvider>
            <div className="site-marquee" aria-hidden="true">
              <div className="site-marquee__inner">TVK Cup deliveries will begin from Pongal (15 January).</div>
            </div>
            <Navbar />
            {children}
            <Layout />
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
